#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely.
# With a sleep 2 between each iteration.
# Displays "I am invincible!!!" when it receives a SIGTERM signal.

while true
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "I am invincible!!!"' SIGTERM
done
